spring.application.name=calofficials
spring.datasource.calgov.jdbc-url=jdbc:sqlite:calgov.db
spring.datasource.calgov.driver-class-name=org.sqlite.JDBC
spring.datasource.comments.jdbc-url=jdbc:sqlite:comments.db
spring.datasource.comments.driver-class-name=org.sqlite.JDBC

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

